apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: greeting
  name: greeting
spec:
  ports:
  - name: 8080-8080
    nodePort: 30007
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greeting
  type: NodePort
status:
  loadBalancer: {}
